site_name: EKS Security Best Practices
repo_name: "aws/aws-eks-best-practices"
repo_url: "https://github.com/aws/aws-eks-best-practices"
theme: 
  name: material
nav:
    - Home: 'index.md'
    - Identity and Access Management: 'iam.md'
    - Pod Security: 'pods.md'
    - Multi-tenancy: 'multitenancy.md'
    - Detective Controls: 'detective.md'
    - Network Security: 'network.md'
    - Data Encryption and Secrets Management: 'data.md'
    - Runtime Security: 'runtime.md'
    - Infrastructure Security: 'hosts.md'
    - Regulatory Compliance: 'compliance.md'
    - Incident Response and Forensics: 'incidents.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
