site_name: EKS Best Practices Guide for Security
repo_name: "aws/aws-eks-best-practices"
repo_url: "https://github.com/aws/aws-eks-best-practices"
edit_uri: edit/master/content/security/docs
theme: 
  name: material
  features: 
    - tabs
nav:
  - Tab 1:
    - Home: 'index.md'
    - Identity and Access Management: 'iam.md'
    - Pod Security: 'pods.md'
    - Multi-tenancy: 'multitenancy.md'
    - Detective Controls: 'detective.md'
    - Network Security: 'network.md'
    - Data Encryption and Secrets Management: 'data.md'
    - Runtime Security: 'runtime.md'
    - Infrastructure Security: 'hosts.md'
    - Regulatory Compliance: 'compliance.md'
    - Incident Response and Forensics: 'incidents.md'
    - Image Security: 'image.md'
  - Tab 2: 
    - Cluster Autoscaling: '../cluster-autoscaling/cluster-autoscaling.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
